Atelier Préparation 
de Données Tabulaires

Partie 1 – Explorer les données

1) Charger les données CSV ;

In [3]:
import pandas as pd;
df = pd.read_csv("../data/smart_building_raw.csv")
print(df)

     id_mesure                 date batiment      type_batiment zone  \
0         1174  2025-02-13 06:00:00       B8           Entrepôt    A
1         1275  2025-03-10 12:00:00       B7             Bureau    D
2         1493  2025-05-04 00:00:00       B5  Centre commercial    B
3         1073  2025-01-19 00:00:00       B6         Université    D
4         1454  2025-04-24 06:00:00       B7             Bureau    D
..         ...                  ...      ...                ...  ...
502       1107  2025-01-27 12:00:00       B2              École    C
503       1271  2025-03-09 12:00:00       B3            Hôpital    B
504       1349  2025-03-29 00:00:00       B5  Centre commercial    B
505       1436  2025-04-19 18:00:00       B7             Bureau    C
506       1103  2025-01-26 12:00:00       B2              École    D

     temperature  humidite     co2  occupation  consommation_kwh  \
0           23.0      40.0   851.0        26.0             138.4
1           28.0      69.0   538.0         0.0             170.2
2           19.5      52.3  1198.0        64.0             149.8
3           20.0      58.4  1014.0        30.0             141.6
4           26.8      70.5   628.0        42.0             228.3
..           ...       ...     ...         ...               ...
502         29.8      66.5   778.0        48.0             243.5
503         21.1      66.3  3900.0        53.0             145.8
504         21.6      61.9   959.0        33.0             100.2
505         21.2      54.5  1066.0        38.0             150.9
506          NaN      64.8   584.0        29.0             163.4

    mode_climatisation etat_systeme jour_semaine alerte
0                  Eco       Normal        Jeudi    Non
1                  Eco       Normal        Lundi    Non
2               Normal       Normal     Dimanche    Oui
3               Normal       Normal     Dimanche    Non
4               Normal       Normal        Jeudi    Non
..                 ...          ...          ...    ...
502             Normal       Normal        Lundi    Non
503                Eco       Alerte     Dimanche    Oui
504                Eco       Normal       Samedi    Non
505              Boost       Normal       Samedi    Oui
506             Normal        Panne     Dimanche    Non

[507 rows x 14 columns]

2) Afficher les premières lignes du dataset ;

In [4]:
df.head()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
0,1174,2025-02-13 06:00:00,B8,Entrepôt,A,23.0,40.0,851.0,26.0,138.4,Eco,Normal,Jeudi,Non
1,1275,2025-03-10 12:00:00,B7,Bureau,D,28.0,69.0,538.0,0.0,170.2,Eco,Normal,Lundi,Non
2,1493,2025-05-04 00:00:00,B5,Centre commercial,B,19.5,52.3,1198.0,64.0,149.8,Normal,Normal,Dimanche,Oui
3,1073,2025-01-19 00:00:00,B6,Université,D,20.0,58.4,1014.0,30.0,141.6,Normal,Normal,Dimanche,Non
4,1454,2025-04-24 06:00:00,B7,Bureau,D,26.8,70.5,628.0,42.0,228.3,Normal,Normal,Jeudi,Non

3) Afficher les dernières lignes du dataset ;

In [5]:
df.tail()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
502,1107,2025-01-27 12:00:00,B2,École,C,29.8,66.5,778.0,48.0,243.5,Normal,Normal,Lundi,Non
503,1271,2025-03-09 12:00:00,B3,Hôpital,B,21.1,66.3,3900.0,53.0,145.8,Eco,Alerte,Dimanche,Oui
504,1349,2025-03-29 00:00:00,B5,Centre commercial,B,21.6,61.9,959.0,33.0,100.2,Eco,Normal,Samedi,Non
505,1436,2025-04-19 18:00:00,B7,Bureau,C,21.2,54.5,1066.0,38.0,150.9,Boost,Normal,Samedi,Oui
506,1103,2025-01-26 12:00:00,B2,École,D,NaN,64.8,584.0,29.0,163.4,Normal,Panne,Dimanche,Non

4) Combien d'observations contient le dataset ?

In [18]:
print(df.shape)
print(len(df))
df.info()

(507, 14)
507
<class 'pandas.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_mesure           507 non-null    int64
 1   date                507 non-null    str
 2   batiment            507 non-null    str
 3   type_batiment       503 non-null    str
 4   zone                507 non-null    str
 5   temperature         495 non-null    float64
 6   humidite            496 non-null    float64
 7   co2                 500 non-null    float64
 8   occupation          501 non-null    float64
 9   consommation_kwh    502 non-null    float64
 10  mode_climatisation  502 non-null    str
 11  etat_systeme        507 non-null    str
 12  jour_semaine        502 non-null    str
 13  alerte              507 non-null    str
dtypes: float64(5), int64(1), str(8)
memory usage: 55.6 KB

5) Combien de variables possède le dataset ?

In [19]:
df.shape[1]

14

6) Identifier les variables numériques

In [22]:
# Identifier et lister les variables numériques
variables_numeriques = df.select_dtypes(include=["number"]).columns.tolist()
print(variables_numeriques)

['id_mesure', 'temperature', 'humidite', 'co2', 'occupation', 'consommation_kwh']

7) Identifier les variables catégorielles ;

In [28]:
variables_categorielles = df.select_dtypes(include=['object', 'category'])
print(variables_categorielles)

                    date batiment      type_batiment zone mode_climatisation  \
0    2025-02-13 06:00:00       B8           Entrepôt    A                Eco
1    2025-03-10 12:00:00       B7             Bureau    D                Eco
2    2025-05-04 00:00:00       B5  Centre commercial    B             Normal
3    2025-01-19 00:00:00       B6         Université    D             Normal
4    2025-04-24 06:00:00       B7             Bureau    D             Normal
..                   ...      ...                ...  ...                ...
502  2025-01-27 12:00:00       B2              École    C             Normal
503  2025-03-09 12:00:00       B3            Hôpital    B                Eco
504  2025-03-29 00:00:00       B5  Centre commercial    B                Eco
505  2025-04-19 18:00:00       B7             Bureau    C              Boost
506  2025-01-26 12:00:00       B2              École    D             Normal

    etat_systeme jour_semaine alerte
0         Normal        Jeudi    Non
1         Normal        Lundi    Non
2         Normal     Dimanche    Oui
3         Normal     Dimanche    Non
4         Normal        Jeudi    Non
..           ...          ...    ...
502       Normal        Lundi    Non
503       Alerte     Dimanche    Oui
504       Normal       Samedi    Non
505       Normal       Samedi    Oui
506        Panne     Dimanche    Non

[507 rows x 8 columns]

C:\Users\NGOM PC\AppData\Local\Temp\ipykernel_15184\2307994377.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  variables_categorielles = df.select_dtypes(include=['object', 'category'])

8) Identifier les dates

In [30]:
dates_officielles = df.select_dtypes(include=['datetime', 'datetime64']).columns.tolist()
print(dates_officielles)

[]

9) Identifier les identifiants

In [32]:
# Trouver les colonnes où chaque ligne est unique
identifiants_potentiels = [col for col in df.columns if df[col].nunique() == len(df)]
print(identifiants_potentiels)

[]

10) Déterminer les statistiques : moyenne, médiane, minimum, maximum, écart-type et quartiles.

In [35]:
# Afficher le résumé statistique complet
resume_stat = df.describe()
print(resume_stat)

         id_mesure  temperature    humidite          co2  occupation  \
count   507.000000   495.000000  496.000000   500.000000  501.000000
mean   1251.114398    24.154141   57.864113   844.150000   44.850299
std     144.782769     7.418465   16.026336   582.181386   24.949139
min    1001.000000   -30.000000  -12.000000    89.000000  -20.000000
25%    1125.500000    21.600000   49.275000   623.750000   27.000000
50%    1252.000000    24.000000   57.550000   787.500000   46.000000
75%    1376.500000    26.000000   65.750000   952.000000   61.000000
max    1500.000000    96.000000  160.000000  6000.000000  116.000000

       consommation_kwh
count        502.000000
mean         169.069323
std           53.164294
min         -100.000000
25%          136.875000
50%          169.800000
75%          202.975000
max          336.200000

In [37]:
df.info()

# Valeurs manquantes
print("Valeurs manquantes :",df.isnull().sum())

# Doublons
print("Nombre de doublons :", df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_mesure           507 non-null    int64
 1   date                507 non-null    str
 2   batiment            507 non-null    str
 3   type_batiment       503 non-null    str
 4   zone                507 non-null    str
 5   temperature         495 non-null    float64
 6   humidite            496 non-null    float64
 7   co2                 500 non-null    float64
 8   occupation          501 non-null    float64
 9   consommation_kwh    502 non-null    float64
 10  mode_climatisation  502 non-null    str
 11  etat_systeme        507 non-null    str
 12  jour_semaine        502 non-null    str
 13  alerte              507 non-null    str
dtypes: float64(5), int64(1), str(8)
memory usage: 55.6 KB
Valeurs manquantes : id_mesure              0
date                   0
batiment               0
type_batiment          4
zone                   0
temperature           12
humidite              11
co2                    7
occupation             6
consommation_kwh       5
mode_climatisation     5
etat_systeme           0
jour_semaine           5
alerte                 0
dtype: int64
Nombre de doublons : 7